const KEY='orkeit_civil_v1';
const state={page:'dashboard',data:JSON.parse(localStorage.getItem(KEY)||'null')||{facilities:[],visits:[]}};
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(){localStorage.setItem(KEY,JSON.stringify(state.data));}
function toast(m){const e=document.createElement('div');e.className='toast';e.textContent=m;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}
function today(){return new Date().toISOString().slice(0,10)}
function id(prefix){return prefix+'-'+Date.now().toString(36).toUpperCase()}
function badge(s){const map={ممتاز:'ok',جيد:'ok',يحتاج_صيانة:'warn',غير_مطابق:'bad',مكتمل:'ok',قيد_المراجعة:'warn'};return '<span class="badge '+(map[s]||'info')+'">'+esc(s)+'</span>'}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
function render(){
 document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page));
 const titles={dashboard:'لوحة التحكم',visits:'إدارة الزيارات',facilities:'المنشآت والعملاء',map:'خريطة المواقع',reports:'التقارير'};
 $('#title').textContent=titles[state.page]||'لوحة التحكم';
 const f={dashboard:dashboard,visits:visits,facilities:facilities,map:mapPage,reports:reports}[state.page]; $('#content').innerHTML=f(); if(state.page==='map') initMap();
}
function dashboard(){
 const fs=state.data.facilities,vs=state.data.visits;
 return '<div class="welcome"><div><h3>مرحباً بك في نظام أوريكيت</h3><p>إدارة الزيارات والفحص الوقائي لأنظمة السلامة والدفاع المدني من مكان واحد.</p></div><button class="primary" onclick="newVisit()">+ تسجيل زيارة</button></div>'+
 '<div class="stats"><div class="stat"><div class="icon">▣</div><span>إجمالي المنشآت</span><b>'+fs.length+'</b></div><div class="stat"><div class="icon">✓</div><span>زيارات مسجلة</span><b>'+vs.length+'</b></div><div class="stat"><div class="icon">!</div><span>تحتاج متابعة</span><b>'+vs.filter(v=>v.status!=='مكتمل').length+'</b></div><div class="stat"><div class="icon">⌖</div><span>مواقع محددة</span><b>'+fs.filter(f=>f.lat).length+'</b></div></div>'+
 '<div class="cols"><div class="panel"><div class="panel-head"><h3>آخر الزيارات</h3><button class="secondary" onclick="state.page=\'visits\';render()">عرض الكل</button></div>'+visitTable(vs.slice(-6).reverse())+'</div><div class="panel"><div class="panel-head"><h3>اختصارات</h3></div><div class="mini-list"><button class="mini-item" onclick="newFacility()">إضافة منشأة <b>＋</b></button><button class="mini-item" onclick="newVisit()">تسجيل زيارة <b>＋</b></button><button class="mini-item" onclick="state.page=\'map\';render()">فتح الخريطة <b>⌖</b></button></div></div></div>';
}
function visitTable(rows){if(!rows.length)return '<div class="empty">لا توجد زيارات حتى الآن.</div>';return '<div class="table-wrap"><table><thead><tr><th>رقم الزيارة</th><th>المنشأة</th><th>التاريخ</th><th>الفاحص</th><th>الحالة</th><th></th></tr></thead><tbody>'+rows.map(v=>'<tr><td><b>'+esc(v.id)+'</b></td><td>'+esc(v.facilityName)+'</td><td>'+esc(v.date)+'</td><td>'+esc(v.inspector)+'</td><td>'+badge(v.status)+'</td><td><button class="secondary" onclick="viewVisit(\''+v.id+'\')">عرض</button></td></tr>').join('')+'</tbody></table></div>'}
function visits(){return '<div class="toolbar"><input class="search" id="visitSearch" placeholder="بحث باسم المنشأة أو رقم الزيارة..." oninput="filterVisits()"><button class="primary" onclick="newVisit()">+ زيارة جديدة</button></div><div class="panel" id="visitPanel">'+visitTable(state.data.visits.slice().reverse())+'</div>'}
function filterVisits(){const q=$('#visitSearch').value.toLowerCase();$('#visitPanel').innerHTML=visitTable(state.data.visits.slice().reverse().filter(v=>(v.facilityName+' '+v.id+' '+v.inspector).toLowerCase().includes(q)))}
function facilities(){const fs=state.data.facilities;return '<div class="toolbar"><input class="search" id="facilitySearch" placeholder="بحث باسم المنشأة أو الجوال..." oninput="filterFacilities()"><button class="primary" onclick="newFacility()">+ منشأة جديدة</button></div><div class="panel" id="facilityPanel">'+facilityTable(fs)+'</div>'}
function facilityTable(fs){if(!fs.length)return '<div class="empty">لم تتم إضافة منشآت بعد.</div>';return '<div class="table-wrap"><table><thead><tr><th>المنشأة</th><th>المسؤول</th><th>النشاط</th><th>الجوال</th><th>الترخيص</th><th>الموقع</th><th></th></tr></thead><tbody>'+fs.map(f=>'<tr><td><b>'+esc(f.name)+'</b></td><td>'+esc(f.contact)+'</td><td>'+esc(f.activity)+'</td><td>'+esc(f.phone)+'</td><td>'+badge(f.license)+'</td><td>'+((f.lat)?'✓ محدد':'—')+'</td><td><button class="secondary" onclick="editFacility(\''+f.id+'\')">تعديل</button> <button class="danger" onclick="deleteFacility(\''+f.id+'\')">حذف</button></td></tr>').join('')+'</tbody></table></div>'}
function filterFacilities(){const q=$('#facilitySearch').value.toLowerCase();$('#facilityPanel').innerHTML=facilityTable(state.data.facilities.filter(f=>(f.name+' '+f.phone+' '+f.contact).toLowerCase().includes(q)))}
function facilityForm(f={}){
 return '<h3>'+(f.id?'تعديل المنشأة':'إضافة منشأة جديدة')+'</h3><form id="facilityForm"><div class="form-grid"><div class="field"><label>اسم المنشأة<input name="name" required value="'+esc(f.name||'')+'"></label></div><div class="field"><label>اسم المسؤول<input name="contact" value="'+esc(f.contact||'')+'"></label></div><div class="field"><label>رقم الجوال<input name="phone" value="'+esc(f.phone||'')+'"></label></div><div class="field"><label>نوع النشاط<input name="activity" value="'+esc(f.activity||'')+'" placeholder="مطعم، مستودع، فندق..."></label></div><div class="field"><label>حالة ترخيص الدفاع المدني<select name="license"><option>ممتاز</option><option>جيد</option><option>يحتاج_صيانة</option><option>غير_مطابق</option></select></label></div><div class="field"><label>تاريخ انتهاء الترخيص<input name="licenseExpiry" type="date" value="'+esc(f.licenseExpiry||'')+'"></label></div><div class="field"><label>خط العرض<input name="lat" type="number" step="any" value="'+esc(f.lat||'')+'"></label></div><div class="field"><label>خط الطول<input name="lng" type="number" step="any" value="'+esc(f.lng||'')+'"></label></div><div class="field full"><label>العنوان<input name="address" value="'+esc(f.address||'')+'"></label></div><div class="field full"><label>ملاحظات<textarea name="notes">'+esc(f.notes||'')+'</textarea></label></div></div><button class="primary wide">حفظ المنشأة</button></form>';
}
function newFacility(){openModal(facilityForm());$('#facilityForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.id=id('FAC');state.data.facilities.push(o);save();closeModal();render();toast('تم حفظ المنشأة')}}
function editFacility(i){const f=state.data.facilities.find(x=>x.id===i);openModal(facilityForm(f));$('#facilityForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));Object.assign(f,o);save();closeModal();render();toast('تم تحديث المنشأة')}}
function deleteFacility(i){if(confirm('حذف المنشأة؟')){state.data.facilities=state.data.facilities.filter(x=>x.id!==i);save();render()}}
function newVisit(){
 if(!state.data.facilities.length){toast('أضف منشأة أولاً');return}
 const options=state.data.facilities.map(f=>'<option value="'+esc(f.id)+'">'+esc(f.name)+'</option>').join('');
 openModal('<h3>تسجيل زيارة دفاع مدني</h3><form id="visitForm"><div class="form-grid"><div class="field"><label>المنشأة<select name="facilityId">'+options+'</select></label></div><div class="field"><label>تاريخ الزيارة<input name="date" type="date" value="'+today()+'" required></label></div><div class="field"><label>اسم الفاحص<input name="inspector" value="مندوب أوريكيت"></label></div><div class="field"><label>حالة الزيارة<select name="status"><option>مكتمل</option><option>قيد_المراجعة</option></select></label></div><div class="field full"><label>أنظمة السلامة التي تم فحصها</label><div class="check-grid">'+['نظام إنذار الحريق','كواشف الدخان','شبكة الرش الآلي','مضخات الحريق','طفايات الحريق','مخارج الطوارئ','إنارة الطوارئ','لوحات التحكم'].map((x,i)=>'<label class="check"><input type="checkbox" name="systems" value="'+x+'" '+(i<5?'checked':'')+'> '+x+'</label>').join('')+'</div></div><div class="field full"><label>نتيجة الفحص<select name="result"><option>جيد</option><option>ممتاز</option><option>يحتاج_صيانة</option><option>غير_مطابق</option></select></label></div><div class="field full"><label>الملاحظات والتوصيات<textarea name="notes" placeholder="اكتب الملاحظات والأعمال المطلوبة..."></textarea></label></div></div><button class="primary wide">حفظ الزيارة وإصدار التقرير</button></form>');
 $('#visitForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.id=id('VIS');o.systems=[...e.target.querySelectorAll('[name="systems"]:checked')].map(x=>x.value);o.facilityName=state.data.facilities.find(f=>f.id===o.facilityId)?.name||'';state.data.visits.push(o);save();closeModal();render();toast('تم تسجيل الزيارة بنجاح');setTimeout(()=>viewVisit(o.id),150)}
}
function viewVisit(i){const v=state.data.visits.find(x=>x.id===i),f=state.data.facilities.find(x=>x.id===v.facilityId)||{};openModal('<div class="report-sheet"><div class="report-head"><div><div class="report-logo">ORKEIT</div><small>للمقاولات العامة وخدمات السلامة</small></div><div><b>تقرير زيارة دفاع مدني</b><br><small>'+esc(v.id)+'</small></div></div><div class="report-row"><div><b>المنشأة:</b> '+esc(f.name||v.facilityName)+'</div><div><b>التاريخ:</b> '+esc(v.date)+'</div><div><b>المسؤول:</b> '+esc(f.contact||'—')+'</div><div><b>الفاحص:</b> '+esc(v.inspector)+'</div><div><b>العنوان:</b> '+esc(f.address||'—')+'</div><div><b>نتيجة الفحص:</b> '+badge(v.result)+'</div></div><div class="report-section"><h4>أنظمة السلامة المفحوصة</h4><p>'+v.systems.map(esc).join(' • ')+'</p></div><div class="report-section"><h4>الملاحظات والتوصيات</h4><p>'+esc(v.notes||'لا توجد ملاحظات مسجلة.')+'</p></div><div class="report-section"><h4>اعتماد الزيارة</h4><div class="signature">توقيع ممثل أوريكيت</div></div><button class="primary no-print" onclick="window.print()">طباعة / حفظ PDF</button></div>')}
function mapPage(){return '<div class="panel"><div class="panel-head"><div><h3>خريطة منشآت أوريكيت</h3><small>يمكن تحديد الإحداثيات من نموذج المنشأة.</small></div><button class="secondary" onclick="locateUser()">موقعي الحالي</button></div><div id="map" class="map"></div></div>'}
function initMap(){const map=L.map('map').setView([24.7136,46.6753],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);state.data.facilities.filter(f=>f.lat&&f.lng).forEach(f=>L.marker([+f.lat,+f.lng]).addTo(map).bindPopup('<b>'+esc(f.name)+'</b><br>'+esc(f.phone||'')));}
function locateUser(){if(!navigator.geolocation){toast('المتصفح لا يدعم الموقع');return}navigator.geolocation.getCurrentPosition(p=>toast('تم تحديد موقعك: '+p.coords.latitude.toFixed(5)+', '+p.coords.longitude.toFixed(5)),()=>toast('تعذر الوصول إلى الموقع'))}
function reports(){const vs=state.data.visits;return '<div class="stats"><div class="stat"><span>إجمالي الزيارات</span><b>'+vs.length+'</b></div><div class="stat"><span>مكتملة</span><b>'+vs.filter(v=>v.status==='مكتمل').length+'</b></div><div class="stat"><span>يحتاج صيانة</span><b>'+vs.filter(v=>v.result==='يحتاج_صيانة').length+'</b></div><div class="stat"><span>غير مطابق</span><b>'+vs.filter(v=>v.result==='غير_مطابق').length+'</b></div></div><div class="panel"><div class="panel-head"><h3>سجل التقارير</h3><button class="primary" onclick="exportCSV()">تصدير CSV</button></div>'+visitTable(vs.slice().reverse())+'</div>'}
function exportCSV(){const rows=[['رقم الزيارة','المنشأة','التاريخ','الفاحص','النتيجة','الحالة','الملاحظات'],...state.data.visits.map(v=>[v.id,v.facilityName,v.date,v.inspector,v.result,v.status,v.notes||''])];const csv='\ufeff'+rows.map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='orkeit-visits.csv';a.click();URL.revokeObjectURL(a.href)}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});
$('#close').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
$('#loginForm').onsubmit=e=>{e.preventDefault();$('#login').classList.add('hidden');$('#app').classList.remove('hidden');render()};
$('#logout').onclick=()=>{location.reload()};
setInterval(()=>{$('#clock').textContent=new Date().toLocaleString('ar-SA',{dateStyle:'medium',timeStyle:'short'})},1000);
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installBtn').classList.remove('hidden');});$('#installBtn').onclick=async()=>{if(deferred){deferred.prompt();deferred=null}};
window.newVisit=newVisit;window.newFacility=newFacility;window.editFacility=editFacility;window.deleteFacility=deleteFacility;window.viewVisit=viewVisit;window.filterVisits=filterVisits;window.filterFacilities=filterFacilities;window.exportCSV=exportCSV;window.locateUser=locateUser;window.state=state;render();